export * from "./GBodegas"
export * from "./DispatchBodega"
export * from "./PedidoBodega"
export * from "./PedidoBodegaSkeleton"
export * from "./DeletePedidoBodega"
export * from "./ObsBodega"
export * from "./ContextsBodega"
export * from "./CompletePedidoBodega"